[package]
name = "veritas"
version = "0.1.0"
edition = "2021"

[dependencies]
step-ingestooor-sdk = { package = "step-ingestooor-sdk", git = "https://github.com/step-finance/step-common-rust.git", rev = "c11cd1372c9b38fde63863f8c30f0936e92d6616" }

solana-transaction-status = "=2.0.13"
solana-program = "=2.0.13"
solana-sdk = "=2.0.13"
solana-client = "=2.0.13"

[patch.crates-io]
solana-transaction-status = { git = 'https://github.com/step-finance/agave', rev = "6eab71f06cd4cf6a8beef47ca8dd056ae3b1f011" }
solana-program = { git = 'https://github.com/step-finance/agave', rev = "6eab71f06cd4cf6a8beef47ca8dd056ae3b1f011" }
solana-sdk = { git = 'https://github.com/step-finance/agave', rev = "6eab71f06cd4cf6a8beef47ca8dd056ae3b1f011" }
solana-client = { git = 'https://github.com/step-finance/agave', rev = "6eab71f06cd4cf6a8beef47ca8dd056ae3b1f011" }
