[workspace]
members = ["crates/*"]
resolver = "2"
package.version = "1.0.0"

[workspace.lints]
clippy.unwrap_used = "deny"

[profile.release]
lto = true
panic = "abort"

[workspace.dependencies]
step-ingestooor-sdk = { package = "step-ingestooor-sdk", git = "ssh://git@github.com/step-finance/step-common-rust.git", rev = "b9dbf7fe7e40d1ecff7f03110864e4451f4bc934" }
solana-transaction-status = "=2.2.0"
solana-program = "=2.2.1"
solana-sdk = "=2.2.1"
solana-client = "=2.2.0"
lapin = "2.0.3"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["env", "derive"] }
dotenvy = "0.15.7"
clickhouse = { version = "0.13.1", features = ["native-tls"] }
futures = "0.3.31"
env_logger = "0.11.6"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
petgraph = "0.7.1"
rust_decimal = { version = "1.37.1", features = ["maths"] }
chrono = "0.4.39"
bs58 = "0.5.1"
axum = "0.8.1"
itertools = "0.14.0"

[patch.crates-io]
solana-transaction-status = { git = 'https://github.com/step-finance/agave', rev = "eaba9badbb32a312f2c4c476ae255775a651e631" }
solana-client = { git = 'https://github.com/step-finance/agave', rev = "eaba9badbb32a312f2c4c476ae255775a651e631" }
solana-program = { git = 'https://github.com/step-finance/solana-sdk', rev = "558a5075feced42dd4ed430ab908935d9a6ce922" }
solana-sdk = { git = 'https://github.com/step-finance/solana-sdk', rev = "558a5075feced42dd4ed430ab908935d9a6ce922" }
