[package]
name = "veritas-sdk"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
petgraph = { workspace = true }
tokio = { workspace = true }
rust_decimal = { workspace = true }
chrono = { workspace = true }
